[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python scripts/setup_db.py && gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
DATABASE_PATH = "/data/database.db"
FLASK_ENV = "production"
FLASK_HOST = "0.0.0.0"
PYTHONUNBUFFERED = "1"