[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
DATABASE_PATH = "/app/database.db"
FLASK_ENV = "production"
FLASK_HOST = "0.0.0.0"